Name:           audacious-libkss
Version:        0.1.0
Release:        1%{?dist}
Summary:        KSS input plugin for Audacious using libkss
License:        MIT AND ISC
URL:            https://github.com/ramonsmits/audacious-libkss

# Source is generated by COPR SCM from git repository with submodules
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  cmake >= 3.22
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  audacious-devel >= 4.2

# libkss is bundled as a static library; it is not available as a
# separate package in Fedora and has no stable shared library ABI.
Provides:       bundled(libkss) = 1.2.1

%description
An Audacious input plugin that uses libkss to play KSS music files
(MSX, SMS, Game Gear). Supports PSG, SCC, OPLL/FMPAC, MSX-Audio/OPL
with per-channel stereo panning and NEZplug m3u playlist parsing.

%prep
%autosetup

%conf
%cmake

%build
%cmake_build

%install
%cmake_install

%files
%license LICENSE
%license libkss/LICENSE.md
%doc README.md
%{_libdir}/audacious/Input/kss-libkss.so

%changelog
* Sat Mar 22 2026 Ramon Smits <ramon@ramonsmits.com> - 0.1.0-1
- Initial package
